=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 16 KN/server/hochschule.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!ELEMENT hochschule (studenten, dozenten, vorlesungen, prüfungen)>
<!ELEMENT studenten (student*)>
<!ELEMENT dozenten (dozent*)>
<!ELEMENT vorlesungen (vorlesung*)>
<!ELEMENT prüfungen (prüfung*)>

<!-- Name -->
<!ELEMENT name (nachname, vorname)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>

<!-- Adresse -->
<!ELEMENT adresse (strasse, hausnummer, land?, plz, ort)>
<!ATTLIST adresse
	art (Heimat | Semester) #REQUIRED
>
<!ELEMENT strasse (#PCDATA)>
<!ELEMENT hausnummer (#PCDATA)>
<!ELEMENT land (#PCDATA)>
<!ELEMENT plz (#PCDATA)>
<!ELEMENT ort (#PCDATA)>

<!-- Student -->
<!ELEMENT student (name, adresse, adresse?)>
<!ATTLIST student
	matrikelnr ID #REQUIRED
>

<!-- Dozent -->
<!ELEMENT dozent (name)>
<!ATTLIST dozent
	dozentnr ID #REQUIRED
>

<!-- Vorlesung -->
<!ELEMENT vorlesung (titel, sws, (kurzbeschreibung|link))>
<!ATTLIST vorlesung
	vorlesungnr ID #REQUIRED
	art (Wahl | Pflicht) #REQUIRED
	dozentnr IDREF #REQUIRED
>

<!ELEMENT titel (#PCDATA)>
<!ELEMENT sws (#PCDATA)>
<!ELEMENT kurzbeschreibung (#PCDATA)>
<!ELEMENT link (#PCDATA)>

<!-- Prüfung -->
<!ELEMENT prüfung (note*)>
<!ATTLIST prüfung
	datum CDATA #REQUIRED
	vorlesungnr IDREF #REQUIRED
>

<!-- Note -->
<!ELEMENT note (#PCDATA)>
<!ATTLIST note
	matrikelnr IDREF #REQUIRED
>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/TheCountAgain/Aufgabe 10/studium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hochschule SYSTEM "hochschule.dtd">
<hochschule>
	<studenten>
		<student matrikelnr="M3583821">
			<name>
				<nachname>Backi</nachname>
				<vorname>Christian</vorname>
			</name>
			<anschrift typ="heim">
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
				<strasse>Meine Straße</strasse>
				<hausnummer>1</hausnummer>
			</anschrift>
			<anschrift typ="semester">
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
				<strasse>Meine andere Straße</strasse>
				<hausnummer>1</hausnummer>
			</anschrift>
		</student>
		
		<student matrikelnr="M3583822">
			<name>
				<nachname>Schmidt</nachname>
				<vorname>Benedikt</vorname>
			</name>
			<anschrift typ="heim">
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
				<strasse>Meine Straße</strasse>
				<hausnummer>1</hausnummer>
			</anschrift>
		</student>
	</studenten>

	<!-- Dozenten -->
	<dozenten>
		<dozent dozentnr="D0">
			<name>
				<nachname>Steuer</nachname>
				<vorname>Tim</vorname>
			</name>
		</dozent>
		<dozent dozentnr="D1">
			<name>
				<nachname>Kant</nachname>
				<vorname>Emanuel</vorname>
			</name>
		</dozent>
	</dozenten>

	<vorlesungen>
		<vorlesung vorlesungnr="V0" typ="pflicht" dozentnr="D0">
			<titel>Rechnernetze</titel>
			<sws>4</sws>
			<kurzbeschreibung>Kurze Beschreibung</kurzbeschreibung>
		</vorlesung>
		<vorlesung vorlesungnr="V1" typ="wahlpflicht" dozentnr="D1">
			<titel>Programmierung 4</titel>
			<sws>4</sws>
			<kurzbeschreibung>Programmierung 4 bei Herrn Folz</kurzbeschreibung>
		</vorlesung>
	</vorlesungen>
	<!-- Vorlesungen -->

	<prüfungen>
		<prüfung vorlesung="V0" datum="2013-10-10">
			<note teilnehmer="M3583821">1</note>
			<note teilnehmer="M3583822">1</note>
		</prüfung>
	</prüfungen>
</hochschule>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 16 KN/hochschule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hochschule SYSTEM "hochschule.dtd">
<hochschule>
	<studenten>
		<student matrikelnr="S3583767">
			<name>
				<nachname>Noll</nachname>
				<vorname>Kevin</vorname>
			</name>
			<adresse art="Heimat">
				<strasse>Seckentalstrasse</strasse>
				<hausnummer>19</hausnummer>
				<land>Deutschland</land>
				<plz>66440</plz>
				<ort>NWB</ort>
			</adresse>
		</student>
	</studenten>

	<dozenten>
		<dozent dozentnr="D1234">
			<name>
				<nachname>Folz</nachname>
				<vorname>Helmut</vorname>
			</name>
		</dozent>
		<dozent dozentnr="D1337">
			<name>
				<nachname>Miede</nachname>
				<vorname>Andre</vorname>
			</name>
		</dozent>
	</dozenten>

	<vorlesungen>
		<vorlesung dozentnr="D1234" art="Wahl" vorlesungnr="V1">
			<titel>Metasprachen</titel>
			<sws>4</sws>
			<link>http://www.htw-saarland.de</link>
		</vorlesung>
	</vorlesungen>
	
	<pr端fungen>
		<pr端fung datum="15.01.2014" vorlesungnr="V1">
			<note matrikelnr="S3583767">1.0</note>
		</pr端fung>
	</pr端fungen>




</hochschule>
