=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 15/hochschule.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="hochschule">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="studenten" />
				<xsd:element ref="dozenten" />
				<xsd:element ref="vorlesungen" />
				<xsd:element ref="prüfungen" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- STUDENTEN -->

	<xsd:element name="studenten">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="student"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="student">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" />
				<xsd:element name="heimatanschrift" type="adresse" maxOccurs="1" />
				<xsd:element name="semesteranschrift" type="adresse" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="matrikelnr" use="required" type="tMatrikelnr" />
		</xsd:complexType>
		<xsd:key name="stundentMatrikelnr">
			<xsd:selector xpath="hochschule/studenten/student" />
			<xsd:field xpath="@matrikelnr" />
		</xsd:key>
		<xsd:keyref name="stundentMatrikelnrRef" refer="stundentMatrikelnr">
			<xsd:selector xpath="hochschule/prüfungen/prüfung/note" />
			<xsd:field xpath="@matrikelnr" />
		</xsd:keyref>
	</xsd:element>

	<xsd:element name="name">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nachname" type="xsd:string" />
				<xsd:element name="vorname" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- strasse, hausnummer, land?, plz, ort -->
	<xsd:complexType name="adresse">
		<xsd:sequence>
			<xsd:element name="strasse" type="xsd:string" />
			<xsd:element name="hausnummer" type="xsd:positiveInteger" />
			<xsd:element name="land" type="xsd:string" minOccurs="0" />
			<xsd:element name="plz" type="tPostleitzahl" />
			<xsd:element name="ort" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- DOZENTEN -->

	<xsd:element name="dozenten">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="dozent" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="dozent">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" />
			</xsd:sequence>
			<xsd:attribute name="dozentnr" use="required" type="tDozentnr" />
		</xsd:complexType>
		<xsd:key name="keyDozentnr">
			<xsd:selector xpath="hochschule/dozenten/dozent" />
			<xsd:field xpath="@dozentnr" />
		</xsd:key>
		<xsd:keyref name="keyDozentnrRef" refer="keyDozentnr">
			<xsd:selector xpath="vorlesungen/vorlesung" />
			<xsd:field xpath="@dozentnr" />
		</xsd:keyref>
	</xsd:element>


	<!-- VORLESUNGEN -->

	<xsd:element name="vorlesungen">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="vorlesung" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="vorlesung">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="titel" type="xsd:string" />
				<xsd:element name="sws" type="tSws" />
				<xsd:choice>
					<xsd:element name="kurzbeschreibung" type="xsd:string" />
					<xsd:element name="link" type="xsd:string" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="vorlesungnr" use="required" type="tVorlesungnr" />
			<xsd:attribute name="art" type="tVorlesungsart" use="required" />
			<xsd:attribute name="dozentnr" use="required" />
		</xsd:complexType>
		<xsd:key name="keyVorlesungsnr">
			<xsd:selector xpath="hochschule/vorlesungen/vorlesung" />
			<xsd:field xpath="@vorlesungnr" />
		</xsd:key>
		<xsd:keyref name="keyVorlesungsnrRef" refer="keyVorlesungsnr">
			<xsd:selector xpath="hochschule/prüfungen/prüfung" />
			<xsd:field xpath="@vorlesungnr" />
		</xsd:keyref>
	</xsd:element>


	<!-- PRÜFUNGEN -->

	<xsd:element name="prüfungen">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="prüfung" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="prüfung">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="note" />
			</xsd:sequence>
			<xsd:attribute name="datum" type="xsd:date" />
			<xsd:attribute name="vorlesungnr" type="tVorlesungnr" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="note">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:decimal">
					<xsd:attribute name="matrikelnr" type="tMatrikelnr" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<!-- TYPEN -->

	<xsd:simpleType name="tPostleitzahl">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{5}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tSws">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{1}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tMatrikelnr">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{7}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tDozentnr">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{3}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tVorlesungnr">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(\S{3}\d{3})|(\S{5}\d{2})" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tVorlesungsart">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="Wahl|Pflicht" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 15/hochschule_falsch1.xml
<?xml version="1.0" encoding="UTF-8"?>
<hochschule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hochschule.xsd">

	<!-- Studenten -->
	<studenten>
		<student matrikelnr="3583821">
			<name>
				<!-- vertauscht -->
				<vorname>Benedikt</vorname>
				<nachname>Schmidt</nachname>
			</name>
			<heimatanschrift>
				<strasse>Zum Bremmenfeld</strasse>
				<hausnummer>14</hausnummer>
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</heimatanschrift>
			<semesteranschrift>
				<strasse>Hauptstraße</strasse>
				<hausnummer>12</hausnummer>
				<land>Deutschland</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</semesteranschrift>
		</student>
		<!-- nur 7stellige Zahlen erlaubt -->
		<student matrikelnr="FALSCH">
			<name>
				<nachname>Noll</nachname>
				<vorname>Kevin</vorname>
			</name>
			<!-- Semesteranschrift geht nur,wenn auch vorher eine Heimanschrift vorhanden ist -->
			<semesteranschrift>
				<strasse>Parkstraße</strasse>
				<hausnummer>1</hausnummer>
				<land>DE</land>
				<plz>12345</plz>
				<ort>Heimat</ort>
			</semesteranschrift>
		</student>
		<student matrikelnr="3583801">
			<name>
				<nachname>Backes</nachname>
				<vorname>Christian</vorname>
			</name>
			<heimatanschrift>
				<strasse>Lindenallee</strasse>
				<hausnummer>21</hausnummer>
				<land>DE</land>
				<plz>66538</plz>
				<ort>Neunkirchen</ort>
			</heimatanschrift>
		</student>
	</studenten>

	<!-- Dozenten -->
	<dozenten>
		<!-- nur 3stellige Zahlen erlaubt -->
		<dozent dozentnr="264AAA">
			<name>
				<nachname>Folz</nachname>
				<vorname>Helmut</vorname>
			</name>
		</dozent>
		<dozent dozentnr="239">
			<name>
				<!-- vertauscht -->
				<vorname>Wolfgang</vorname>
				<nachname>Pauly</nachname>
			</name>
		</dozent>
		<dozent dozentnr="782">
			<name>
				<nachname>Miede</nachname>
				<vorname>André</vorname>
			</name>
		</dozent>
		<dozent dozentnr="313">
			<!-- Name fehlt komplett -->
		</dozent>

	</dozenten>

	<!-- Vorlesungen -->
	<vorlesungen>
		<vorlesung vorlesungnr="PIB120" art="Pflicht" dozentnr="264">
			<titel>Programmierung 1</titel>
			<sws>5</sws>
			<kurzbeschreibung>Einführung in die Programmierung mit Java</kurzbeschreibung>
		</vorlesung>

		<!-- entspricht nicht dem Muster-->
		<vorlesung vorlesungnr="PIB999999" art="Pflicht" dozentnr="239">
			<titel>Betriebssystemeinführung</titel>
			<sws>2</sws>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=pbseinf&amp;lang=de</link>
			<kurzbeschreibung>Einführung in die Spieleentwicklung</kurzbeschreibung>
			<!-- Kurzbeschreibung UND Link gehen nicht! -->
		</vorlesung>

		<vorlesung vorlesungnr="PIBWI43" art="Wahl" dozentnr="782">
			<titel>Game Design And Development</titel>
			<sws>2</sws>
			<!-- Kurzbeschreibung oder Link fehlen -->
		</vorlesung>

		<!-- Referenz für Dozent 999 kann nicht gefunden werden -->
		<vorlesung vorlesungnr="PIB423" art="Pflicht" dozentnr="999">
		 	<!-- sws muss unter den Titel -->
			<sws>2</sws>
			<titel>Systemmanagement und Sicherheit</titel>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=sysi&amp;lang=de</link>
		</vorlesung>

	</vorlesungen>

	<!-- Prüfungen -->
	<prüfungen>
		<prüfung datum="2013-10-10" vorlesungnr="PIB120">
			<note matrikelnr="3583821">15</note>
			<note matrikelnr="3583800">16</note>
			<note matrikelnr="3583801">12</note>
		</prüfung>
		<!-- PIB110 gibt es nicht -->
		<prüfung datum="2012-12-12" vorlesungnr="PIB110">
			<note matrikelnr="3583821">10</note>
			<note matrikelnr="3583800">12</note>
			<note matrikelnr="3583801">20</note>
		</prüfung>
		<prüfung datum="2011-11-11" vorlesungnr="PIBWI43">
			<note matrikelnr="3583821">9</note>
			<note matrikelnr="3583800">13</note>
			<note matrikelnr="3583801">20</note>
		</prüfung>

		<prüfung datum="2012-01-01" vorlesungnr="PIB423">
			<!-- Dozent mit dieser Nummer nicht vorhanden -->
			<note matrikelnr="3583800">11</note>
		</prüfung>

	</prüfungen>
</hochschule>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 15/hochschule.xml
<?xml version="1.0" encoding="UTF-8"?>
<hochschule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hochschule.xsd">

	<!-- Studenten -->
	<studenten>
		<student matrikelnr="3583821">
			<name>
				<nachname>Schmidt</nachname>
				<vorname>Benedikt</vorname>
			</name>
			<heimatanschrift>
				<strasse>Zum Bremmenfeld</strasse>
				<hausnummer>14</hausnummer>
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</heimatanschrift>
			<semesteranschrift>
				<strasse>Hauptstraße</strasse>
				<hausnummer>12</hausnummer>
				<land>Deutschland</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</semesteranschrift>
		</student>
		<student matrikelnr="3583800">
			<name>
				<nachname>Noll</nachname>
				<vorname>Kevin</vorname>
			</name>
			<heimatanschrift>
				<strasse>Parkstraße</strasse>
				<hausnummer>1</hausnummer>
				<land>DE</land>
				<plz>12345</plz>
				<ort>Heimat</ort>
			</heimatanschrift>
		</student>
		<student matrikelnr="3583801">
			<name>
				<nachname>Backes</nachname>
				<vorname>Christian</vorname>
			</name>
			<heimatanschrift>
				<strasse>Lindenallee</strasse>
				<hausnummer>21</hausnummer>
				<land>DE</land>
				<plz>66538</plz>
				<ort>Neunkirchen</ort>
			</heimatanschrift>
		</student>
	</studenten>

	<!-- Dozenten -->
	<dozenten>
		<dozent dozentnr="264">
			<name>
				<nachname>Folz</nachname>
				<vorname>Helmut</vorname>
			</name>
		</dozent>
		<dozent dozentnr="239">
			<name>
				<nachname>Pauly</nachname>
				<vorname>Wolfgang</vorname>
			</name>
		</dozent>
		<dozent dozentnr="782">
			<name>
				<nachname>Miede</nachname>
				<vorname>André</vorname>
			</name>
		</dozent>
		<dozent dozentnr="313">
			<name>
				<nachname>Weber</nachname>
				<vorname>Damian</vorname>
			</name>
		</dozent>

	</dozenten>

	<!-- Vorlesungen -->
	<vorlesungen>
		<vorlesung vorlesungnr="PIB120" art="Pflicht" dozentnr="D264">
			<titel>Programmierung 1</titel>
			<sws>5</sws>
			<kurzbeschreibung>Einführung in die Programmierung mit Java</kurzbeschreibung>
		</vorlesung>

		<vorlesung vorlesungnr="PIB110" art="Pflicht" dozentnr="D239">
			<titel>Betriebssystemeinführung</titel>
			<sws>2</sws>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=pbseinf&amp;lang=de</link>
		</vorlesung>

		<vorlesung vorlesungnr="PIBWI43" art="Wahl" dozentnr="D782">
			<titel>Game Design And Development</titel>
			<sws>2</sws>
			<kurzbeschreibung>Einführung in die Spieleentwicklung</kurzbeschreibung>
		</vorlesung>

		<vorlesung vorlesungnr="PIB423" art="Pflicht" dozentnr="D313">
			<titel>Systemmanagement und Sicherheit</titel>
			<sws>2</sws>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=sysi&amp;lang=de</link>
		</vorlesung>

	</vorlesungen>

	<!-- Prüfungen -->
	<prüfungen>
		<prüfung datum="2013-10-10" vorlesungnr="PIB120">
			<note matrikelnr="3583821">15</note>
			<note matrikelnr="3583800">16</note>
			<note matrikelnr="3583801">12</note>
		</prüfung>
		<prüfung datum="2012-12-12" vorlesungnr="PIB110">
			<note matrikelnr="3583821">10</note>
			<note matrikelnr="3583800">12</note>
			<note matrikelnr="3583801">20</note>
		</prüfung>
		<prüfung datum="2011-11-11" vorlesungnr="PIBWI43">
			<note matrikelnr="3583821">9</note>
			<note matrikelnr="3583800">13</note>
			<note matrikelnr="3583801">20</note>
		</prüfung>

		<prüfung datum="2012-01-01" vorlesungnr="PIB423">
			<note matrikelnr="3583800">11</note>
		</prüfung>

	</prüfungen>
</hochschule>
