<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE benutzer [
<!ELEMENT name (vorname, nachname)*>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>
<!ATTLIST name alter CDATA #REQUIRED>
]>

<!-- Wurzelelement, darf nur genau eines geben! -->
<!-- ACHTUNG: die Reihenfolge laut DTD muss eingehalten werden -->
<benutzer>
	<name alter="17">
		<vorname>Max</vorname>
		<nachname>Power</nachname>
	</name>
	
	<name alter="21">
		<vorname>Dr</vorname>
		<nachname>Mundo</nachname>
	</name>
</benutzer>