=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe12/A14/A14.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="katalog">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="buch" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="buch">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="autor" />
				<xsd:element name="titel" type="xsd:string"/>
				<xsd:element name="untertitel" type="xsd:string" minOccurs="0"/>
				<xsd:element name="verlag" type="xsd:string" />
				<xsd:element name="aufnahmedatum" type="xsd:string"/>
				<xsd:element name="bemerkung" type="xsd:string" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="signatur" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="autor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="vorname" type="xsd:string" />
				<xsd:element name="nachname" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe12/A14/A14.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Beseitigen Sie alle Fehler! -->
<katalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="A14.xsd">
	<buch>
		<autor>
			<vorname>asd</vorname>
			<nachname>asd</nachname>
		</autor>
		<titel>asd</titel>
		<untertitel>asd</untertitel>
		<verlag>asd</verlag>
		<aufnahmedatum>asdasd</aufnahmedatum>
		<bemerkung>tewtset</bemerkung>
	</buch>
</katalog>
