=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe2/A5/hochschule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT hochschule (student, dozent, vorlesung, prüfung)>

<!ELEMENT student (name, anschrift, anschrift?)>
<!ATTLIST student matrikelNr ID #REQUIRED>

<!ELEMENT anschrift (länderkürzel?, plz, ort, straße, hausnummer)>
<!ATTLIST anschrift typ (Heimanschrift | Semesteranschrift) #REQUIRED>
<!ELEMENT länderkürzel (#PCDATA)>
<!ELEMENT plz (#PCDATA)>
<!ELEMENT ort (#PCDATA)>
<!ELEMENT straße (#PCDATA)>
<!ELEMENT hausnummer (#PCDATA)>


<!ELEMENT name (vorname, nachname)>
<!ATTLIST dozent dozentID ID #REQUIRED>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>

<!ELEMENT dozent (name)>

<!ELEMENT vorlesung (titel, sws, (kurzbeschreibung | link))>
<!ATTLIST vorlesung 
		vorlesungsNr ID #REQUIRED
		art (Pflicht | Wahlpflicht) #REQUIRED
		dozentID IDREF #REQUIRED>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT sws (#PCDATA)>
<!ELEMENT kurzbeschreibung (#PCDATA)>
<!ELEMENT link (#PCDATA)>

<!ELEMENT prüfung (datum, teilnehmer*)>
<!ATTLIST prüfung vorlesungsNr IDREF #REQUIRED>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT teilnehmer (note)>
<!ATTLIST teilnehmer matrikelNr IDREF #REQUIRED>
<!ELEMENT note (#PCDATA)>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe7/A10/hochschule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hochschule SYSTEM "hochschule.dtd">
<hochschule>
	<student matrikelNr="d3583767">
		<name>
			<vorname>Kevin</vorname>
			<nachname>Noll</nachname>
		</name>
		<anschrift typ="Heimanschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66440</plz>
			<ort>Blieskastel</ort>
			<straße>Seckentalstrasse</straße>
			<hausnummer>19</hausnummer>
		</anschrift>
		<anschrift typ="Semesteranschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66440</plz>
			<ort>Blieskastel</ort>
			<straße>Seckentalstrasse</straße>
			<hausnummer>19</hausnummer>
		</anschrift>
	</student>
	<student matrikelNr="d123456">
		<name>
			<vorname>Chirs</vorname>
			<nachname>Backi</nachname>
		</name>
		<anschrift typ="Heimanschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66386</plz>
			<ort>IGB</ort>
			<straße>Blastr</straße>
			<hausnummer>123</hausnummer>
		</anschrift>
		<anschrift typ="Semesteranschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66111</plz>
			<ort>SB</ort>
			<straße>Unistr</straße>
			<hausnummer>1</hausnummer>
		</anschrift>
	</student>

	<dozent dozentID="D01">
		<name>
			<vorname>André</vorname>
			<nachname>Miede</nachname>
		</name>
	</dozent>
	<dozent dozentID="D02">
		<name>
			<vorname>Helmut</vorname>
			<nachname>Folz</nachname>
		</name>
	</dozent>

	<vorlesung vorlesungsNr="V01" art="Pflicht" dozentID="D01">
		<titel>Prog1</titel>
		<sws>4</sws>
		<link>http://asd</link>
	</vorlesung>
		<vorlesung vorlesungsNr="V02" art="Wahlpflicht" dozentID="D02">
		<titel>Prog2</titel>
		<sws>3</sws>
		<kurzbeschreibung>wurst</kurzbeschreibung>
	</vorlesung>

	<prüfung vorlesungsNr="V01">
		<datum>20.01.2014</datum>
		<teilnehmer matrikelNr="d3583767">
			<note>20</note>
		</teilnehmer>
	</prüfung>
		<prüfung vorlesungsNr="V02">
		<datum>20.01.2015</datum>
		<teilnehmer matrikelNr="d123456">
			<note>5</note>
		</teilnehmer>
	</prüfung>
</hochschule>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe11/A13/hochschule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE katalog SYSTEM "hochschule.dtd">
<hochschule>

	<!-- Studenten -->
	<studenten>
		<student matrikelnr="M3583821">
			<name>
				<nachname>Schmidt</nachname>
				<vorname>Benedikt</vorname>
			</name>
			<adresse art="Heimat">
				<strasse>Zum Bremmenfeld</strasse>
				<hausnummer>14</hausnummer>
				<land>DE</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</adresse>
			<adresse art="Semester">
				<strasse>Hauptstraße</strasse>
				<hausnummer>12</hausnummer>
				<land>Deutschland</land>
				<plz>66539</plz>
				<ort>Neunkirchen</ort>
			</adresse>
		</student>
		<student matrikelnr="M3583800">
			<name>
				<nachname>Noll</nachname>
				<vorname>Kevin</vorname>
			</name>
			<adresse art="Heimat">
				<strasse>Parkstraße</strasse>
				<hausnummer>1</hausnummer>
				<land>DE</land>
				<plz>123456</plz>
				<ort>Heimat</ort>
			</adresse>
		</student>
		<student matrikelnr="M3583801">
			<name>
				<nachname>Backes</nachname>
				<vorname>Christian</vorname>
			</name>
			<adresse art="Heimat">
				<strasse>Lindenallee</strasse>
				<hausnummer>21</hausnummer>
				<land>DE</land>
				<plz>66538</plz>
				<ort>Neunkirchen</ort>
			</adresse>
		</student>
	</studenten>

	<!-- Dozenten -->
	<dozenten>
		<dozent dozentnr="D264">
			<name>
				<nachname>Folz</nachname>
				<vorname>Helmut</vorname>
			</name>
		</dozent>
		<dozent dozentnr="D239">
			<name>
				<nachname>Pauly</nachname>
				<vorname>Wolfgang</vorname>
			</name>
		</dozent>
		<dozent dozentnr="D782">
			<name>
				<nachname>Miede</nachname>
				<vorname>André</vorname>
			</name>
		</dozent>
		<dozent dozentnr="D313">
			<name>
				<nachname>Weber</nachname>
				<vorname>Damian</vorname>
			</name>
		</dozent>

	</dozenten>

	<!-- Vorlesungen -->
	<vorlesungen>
		<vorlesung vorlesungnr="PIB120" art="Pflicht" dozentnr="D264">
			<titel>Programmierung 1</titel>
			<sws>5</sws>
			<kurzbeschreibung>Einführung in die Programmierung mit Java</kurzbeschreibung>
		</vorlesung>

		<vorlesung vorlesungnr="PIB110" art="Pflicht" dozentnr="D239">
			<titel>Betriebssystemeinführung</titel>
			<sws>2</sws>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=pbseinf&amp;lang=de</link>
		</vorlesung>

		<vorlesung vorlesungnr="PIBWI43" art="Wahl" dozentnr="D782">
			<titel>Game Design And Development</titel>
			<sws>2</sws>
			<kurzbeschreibung>Einführung in die Spieleentwicklung</kurzbeschreibung>
		</vorlesung>
		
		<vorlesung vorlesungnr="PIB423" art="Pflicht" dozentnr="D313">
			<titel>Systemmanagement und Sicherheit</titel>
			<sws>2</sws>
			<link>http://moduldb.htw-saarland.de/cgi-bin/moduldb-c?bkeys=pi&amp;ckeys=sysi&amp;lang=de</link>
		</vorlesung>

	</vorlesungen>

	<!-- Prüfungen -->
	<prüfungen>
		<prüfung datum="2013-10-10" vorlesungnr="PIB120">
			<note matrikelnr="M3583821">15</note>
			<note matrikelnr="M3583800">16</note>
			<note matrikelnr="M3583801">12</note>
		</prüfung>
		<prüfung datum="2012-12-12" vorlesungnr="PIB110">
			<note matrikelnr="M3583821">10</note>
			<note matrikelnr="M3583800">12</note>
			<note matrikelnr="M3583801">20</note>
		</prüfung>
		<prüfung datum="2011-11-11" vorlesungnr="PIBWI43">
			<note matrikelnr="M3583821">9</note>
			<note matrikelnr="M3583800">13</note>
			<note matrikelnr="M3583801">20</note>
		</prüfung>
		
		<prüfung datum="2012-01-01" vorlesungnr="PIB423">
			<note matrikelnr="M3583800">11</note>
		</prüfung>

	</prüfungen>
</hochschule>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe2/A5/hochschule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hochschule SYSTEM "hochschule.dtd">
<hochschule>
	<student matrikelNr="d3583767">
		<name>
			<vorname>Kevin</vorname>
			<nachname>Noll</nachname>
		</name>
		<anschrift typ="Heimanschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66440</plz>
			<ort>Blieskastel</ort>
			<straße>Seckentalstraße</straße>
			<hausnummer>19</hausnummer>
		</anschrift>
		<anschrift typ="Semesteranschrift">
			<länderkürzel>DE</länderkürzel>
			<plz>66440</plz>
			<ort>Blieskastel</ort>
			<straße>Seckentalstraße</straße>
			<hausnummer>19</hausnummer>
		</anschrift>
	</student>

	<dozent dozentID="D01">
		<name>
			<vorname>André</vorname>
			<nachname>Miede</nachname>
		</name>
	</dozent>

	<vorlesung vorlesungsNr="V01" art="Pflicht" dozentID="D01">
		<titel>Prog1</titel>
		<sws>4</sws>
		<link>http://asd</link>
	</vorlesung>

	<prüfung vorlesungsNr="V01">
		<datum>20.01.2014</datum>
		<teilnehmer matrikelNr="d3583767">
			<note>20</note>
		</teilnehmer>
	</prüfung>
</hochschule>
