=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe12/A15/A15.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="hochschule">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="studenten" />
				<xsd:element ref="dozenten" />
				<xsd:element ref="vorlesungen" />
				<xsd:element ref="prüfungen" />
			</xsd:sequence>
		</xsd:complexType>

		<xsd:key name="stundentMatrikelnr">
			<xsd:selector xpath=".//studenten/student" />
			<xsd:field xpath="@matrikelnr" />
		</xsd:key>
		<xsd:keyref name="stundentMatrikelnrRef" refer="stundentMatrikelnr">
			<xsd:selector xpath=".//prüfungen/prüfung/note" />
			<xsd:field xpath="@matrikelnr" />
		</xsd:keyref>

		<xsd:key name="dozentnr">
			<xsd:selector xpath=".//dozenten/dozent" />
			<xsd:field xpath="@dozentnr" />
		</xsd:key>
		<xsd:keyref name="donzentnrref" refer="dozentnr">
			<xsd:selector xpath=".//vorlesungen/vorlesung" />
			<xsd:field xpath="@dozentnr" />
		</xsd:keyref>

		<xsd:key name="vorlesungnr">
			<xsd:selector xpath=".//vorlesungen/vorlesung" />
			<xsd:field xpath="@vorlesungnr" />
		</xsd:key>
		<xsd:keyref name="vorlesungprüfungref" refer="vorlesungnr">
			<xsd:selector xpath=".//prüfungen/prüfung" />
			<xsd:field xpath="@vorlesungnr" />
		</xsd:keyref>

	</xsd:element>


	<xsd:element name="studenten">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="student" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="student">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" />
				<xsd:element name="Heimatadresse" type="adresse" />
				<xsd:element name="Semesteradresse" type="adresse"
					minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="matrikelnr" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="name">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="vorname" type="xsd:string" />
				<xsd:element name="nachname" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="adresse">
		<xsd:sequence>
			<xsd:element name="strasse" type="xsd:string" />
			<xsd:element name="hausnummer" type="xsd:string" />
			<xsd:element name="land" type="xsd:string" minOccurs="0" />
			<xsd:element name="plz" type="xsd:string" />
			<xsd:element name="ort" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="dozenten">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dozent" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="dozent">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" />
			</xsd:sequence>
			<xsd:attribute name="dozentnr" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="vorlesungen">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="vorlesung" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="vorlesung">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="titel" type="xsd:string" />
				<xsd:element name="sws" type="xsd:string" />
				<xsd:choice maxOccurs="1">
					<xsd:element name="kurzbeschreibung" type="xsd:string" />
					<xsd:element name="link" type="xsd:string" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="vorlesungnr" use="required" type="xsd:string" />
			<xsd:attribute name="art" use="required" type="tvorlesungart" />
			<xsd:attribute name="dozentnr" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="tvorlesungart">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Wahl"></xsd:enumeration>
			<xsd:enumeration value="Pflicht"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="prüfungen">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="prüfung" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="prüfung">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="note" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="vorlesungnr" use="required" />
			<xsd:attribute name="datum" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="note">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:decimal">
					<xsd:attribute name="matrikelnr" use="required" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/KN/Aufgabe12/A15/A15.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Beseitigen Sie alle Fehler! -->
<hochschule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="A15.xsd">
	<studenten>
		<student matrikelnr="3583767">
			<name>
				<vorname>Kevin</vorname>
				<nachname>Noll</nachname>
			</name>
			<Heimatadresse>
				<strasse>Seckentalstrasse</strasse>
				<hausnummer>19</hausnummer>
				<land>DE</land>
				<plz>66440</plz>
				<ort>NWB</ort>
			</Heimatadresse>
		</student>
	</studenten>
	<dozenten>
		<dozent dozentnr="D01">
			<name>
				<vorname>Andre</vorname>
				<nachname>Miede</nachname>
			</name>
		</dozent>
	</dozenten>
	<vorlesungen>
		<vorlesung dozentnr="D01" vorlesungnr="V01" art="Wahl">
			<titel>GDD</titel>
			<sws>5</sws>
			<kurzbeschreibung>cool</kurzbeschreibung>
		</vorlesung>
	</vorlesungen>
	<prüfungen>
		<prüfung datum="11.02.2014" vorlesungnr="V01">
			<note matrikelnr="3583767">
				20
			</note>
		</prüfung>
	</prüfungen>
</hochschule>
