=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 07/Benne/studium.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT studium (student*, dozent*, vorlesung*, prüfung*)>

<!-- Student -->
<!ELEMENT student (name, anschrift, anschrift?)>
<!ATTLIST student matrikelnummer ID #REQUIRED>

<!-- Name -->
<!ELEMENT name (vorname, nachname)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>

<!-- Anschrift -->
<!ELEMENT anschrift (land, plz, ort, straße, hausnummer)>
<!ATTLIST anschrift art (heimat | semester) #REQUIRED> 
<!ELEMENT land (#PCDATA)>
<!ELEMENT plz (#PCDATA)>
<!ELEMENT ort (#PCDATA)>
<!ELEMENT straße (#PCDATA)>
<!ELEMENT hausnummer (#PCDATA)>

<!-- Dozent -->
<!ELEMENT dozent (name)> 
<!ATTLIST dozent identifier ID #REQUIRED>

<!-- Vorlesung -->
<!ELEMENT vorlesung (titel, sws, (kurzbeschreibung | link))>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT sws (#PCDATA)>
<!ELEMENT kurzbeschreibung (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST vorlesung
	art (pflicht | wahlpflicht) #REQUIRED
	dozenten IDREFS #REQUIRED
	identifier ID #REQUIRED
>

<!-- Prüfung -->
<!ELEMENT prüfung (datum, teilnahme*)>
<!ELEMENT datum (#PCDATA)>
<!ATTLIST prüfung vorlesung IDREF #REQUIRED>

<!-- Teilnahme -->
<!ELEMENT teilnahme (note)>
<!ATTLIST teilnahme teilnehmer IDREF #REQUIRED>
<!ELEMENT note (#PCDATA)>

=== beneschmidt/Metasprachen/Metasprachen/WebContent/Aufgabe 03/studium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studium SYSTEM "studium.dtd">
<studium>
	<student matrikelnummer="M3583821">
		<name>
			<vorname>Vorname</vorname>
			<nachname>Nachname</nachname>
		</name>
		<anschrift art="heimat">
			<land>DE</land>
			<plz>66539</plz>
			<ort>Neunkirchen</ort>
			<straße>Meine Straße</straße>
			<hausnummer>1</hausnummer>
		</anschrift>
		<anschrift art="semester">
			<land>DE</land>
			<plz>66539</plz>
			<ort>Neunkirchen</ort>
			<straße>Meine andere Straße</straße>
			<hausnummer>1</hausnummer>
		</anschrift>
	</student>
	
	<!-- Dozenten -->
	<dozent identifier="D0">
		<name>
			<vorname>Der</vorname>
			<nachname>Dozent</nachname>
		</name>
	</dozent>
	<dozent identifier="D1">
		<name>
			<vorname>Herr</vorname>
			<nachname>Folz</nachname>
		</name>
	</dozent>
	
	<!-- Vorlesungen -->
	<vorlesung identifier="V0" art="pflicht" dozenten="D0">
		<titel>Rechnernetze</titel>
		<sws>4</sws>
		<kurzbeschreibung>Kurze Beschreibung</kurzbeschreibung>
	</vorlesung>
	<vorlesung identifier="V1" art="wahlpflicht" dozenten="D1">
		<titel>Programmierung 4</titel>
		<sws>4</sws>
		<kurzbeschreibung>Programmierung 4 bei Herrn Folz</kurzbeschreibung>
	</vorlesung>
	
	<prüfung vorlesung="V0">
		<datum>2013-10-10</datum>
		<teilnahme teilnehmer="M3583821">
			<note>1</note>
		</teilnahme>
	</prüfung>
</studium>
